apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    team: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: ibrahimaydemir/ybblog:db
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ybblog-secret
                key: mysql-passwd
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlvolume
      volumes:
      - name: mysqlvolume
        hostPath:
          # directory location on host
          path: /home/ibrahimaydemir/ybblog-secrets
          # this field is optional
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
