---
apiVersion: v1
kind: Secret
metadata:
  name: ybblog-secret
type: Opaque
stringData:
   mysql-user: root
   mysql-passwd: test
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendv1
  labels:
    team: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webv1
  template:
    metadata:
      labels:
        app: webv1
    spec:
      containers:
      - name: webv1
        image: ibrahimaydemir/webproject:v1
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: ybblog-secret
                key: mysql-user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ybblog-secret
                key: mysql-passwd
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webv1
spec:
  selector:
    app: webv1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:  
  name: frontend
spec:
  selector:    
    app: webv1
  type: NodePort
  ports:  
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30036
    protocol: TCP
  
